### ISSUE TITLE
Set up Parse data model interface: users and events

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#10]
Parse backend should match local data models.
Should be able to freely pass data.

**Comment by sandramngo** [comment]
http://blog.parse.com/2014/06/25/login-love-for-your-android-app/?mkt_tok=3RkMMJWWfF9wsRonua7AZKXonjHpfsX86OguW6C3lMI%2F0ER3fOvrPUfGjI4ATsVlI%2BSLDwEYGJlv6SgFTbHGMblmy7gNUxU%3D

**Comment by mydiemho** [comment]
event, user and eventUser model created
