### ISSUE TITLE
Create new events

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#2]
Acceptance Criteria:

0) UI
1) Store event detail

![image](https://cloud.githubusercontent.com/assets/1634185/3451585/c767765a-019b-11e4-80fb-c345d84e6106.png)

**Comment by mydiemho** [comment]
https://github.com/eecsninja/partyview/commit/fc7cfebca8e985f875c03d777ae8909aa2c76fe3

**Comment by mydiemho** [comment]
https://github.com/eecsninja/partyview/commit/9ec7776b17671c81af6c60692d96ff7ab0e6acb8

**Comment by sandramngo** [comment]
https://developers.google.com/maps/documentation/geocoding/#geocoding to get the geo points from an address
