### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#21]

**Comment by mydiemho** [comment]
is this related to https://github.com/eecsninja/partyview/issues/7?

**Comment by simonque** [comment]
Notifications should be supported now.
https://github.com/eecsninja/partyview/commit/9b0dfc6c9d3d6afecafef88c9777506f2affc545
https://github.com/eecsninja/partyview/commit/05ba0e03a6cda3a74a0e6b705011fe112d82b4ff

Still need better handling of them when you click on the notification. Right now it takes you to the home activity rather than to anything specific.

**Comment by simonque** [comment]
This is related to #7, yes. I've added it to the code for #7.

https://github.com/eecsninja/partyview/commit/42b443a957d9f3e650b209131014d7a42c10423c

**Comment by simonque** [comment]
Things left to do (not exhaustive):
1. Handle notification clicks in notification-specific ways.
2. Updated event should send a different notification.

**Comment by simonque** [comment]
Fixed item 2: https://github.com/eecsninja/partyview/commit/c453b6178fc1d4fa8bedeb24526bf95a0f54ee13

**Comment by simonque** [comment]
Notification is now clickable: 
https://github.com/eecsninja/partyview/commit/2d3c78c6d43e8eec5854712dc9c954e810e60a14
