### ISSUE TITLE
Allow resetting of password when signed in

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#24]
Not sure if this is possible directly... might just have to tell parse to send a password reset email...

**Comment by mydiemho** [comment]
parse has an open source login library: phttp://blog.parse.com/2014/06/25/login-love-for-your-android-app/

**Comment by simonque** [comment]
Oops, closed wrong issue.

**Comment by simonque** [comment]
Can one of you figure out how to do this? I need to deal with notifications.

**Comment by mydiemho** [comment]
https://github.com/eecsninja/partyview/commit/fd64bc8d4cc2a48cf461666a995566c67af40069
