### ISSUE TITLE
Login/Signup should handle user errors more clearly

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#25]
Notify the user about what's wrong.
e.g. already existent user/email, wrong password, etc

**Comment by simonque** [comment]
https://github.com/eecsninja/partyview/commit/ad3862087b7d91fae9af966c3e69d629f33bae2c
However, it only shows one message for various failures. No specific reason given.

**Comment by mydiemho** [comment]
this might do more? parse has an open source login library: phttp://blog.parse.com/2014/06/25/login-love-for-your-android-app/

**Comment by simonque** [comment]
Done: https://github.com/eecsninja/partyview/commit/ec45cd5d2c516d23de6c240c177ba13f057357a3
