### ISSUE TITLE
make event details editable in detailed view

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#29]
try to reuse code from new event activity

**Comment by simonque** [comment]
Refactored NewEventActivity into activity + fragment:
https://github.com/eecsninja/partyview/commit/c3c02b2bf1c8f32e7bb18d240b7a69b59f6d875d

**Comment by simonque** [comment]
Load an event for editing in EditEventActivity:
https://github.com/eecsninja/partyview/commit/e4946a53f8b98d37f99e13986dc84b4aa370820f

Doesn't save the event though.
And doesn't display times properly.

**Comment by mydiemho** [comment]
added changes to display time properly https://github.com/eecsninja/partyview/commit/20f68ce45022c1ceb5045b062ebae62a5167f4f2

**Comment by mydiemho** [comment]
please change button text to display "Edit Event"

**Comment by simonque** [comment]
Changed:
https://github.com/eecsninja/partyview/commit/f80994102fe9f2d14fb433bf97f189e62c1ede7b

**Comment by simonque** [comment]
Loading invitees:
https://github.com/eecsninja/partyview/commit/6ffc7bb247dd7afa274e8f68300b99063baf33ed

**Comment by simonque** [comment]
Saving the event, but not updating it in all the activities:
https://github.com/eecsninja/partyview/commit/e580508a1767617d5ae860c673fe66b0d21dbe8f

**Comment by simonque** [comment]
Avoid duplicate EventUsers:
https://github.com/eecsninja/partyview/commit/84da36f32329e3102fb4b9d2c047b791c8d96716

**Comment by simonque** [comment]
Pass the updated event back to parent activities:
https://github.com/eecsninja/partyview/commit/7733e1d42d034bdf4688125117a7480299667f9f

**Comment by simonque** [comment]
Need to add proper notifications for updated events. See #21.
