### ISSUE TITLE
[Android Bootcamp] SMS Group Project Milestone 2

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#30]
cc @nesquena and @thecodepath

**Comment by vibhorB** [comment]
Impressive work so far on the group project. Your team has made great progress and great to see everyone contributing. Hope you guys are proud of what you have learnt and achieved in such short time in the bootcamp.
- Good plan, overall strategy and work distribution. Your goals look realistic and if you continue working at this pace, your team should have a pretty good functional app by Monday night.
- Keep working on integrating the core flows and make sure all pieces fit together perfectly.
- Keep testing the app for thoroughly including invalid inputs also to make sure app doesn't crash and the flow works smoothly

Please remember to submit the GIF walkthrough of your functional app latest by Monday night. I would also encourage you to start thinking about coming up with a user story for the demo day. It is the apps with the most appealing story that gains the most attention on the demo day. Looking forward to seeing your submission this Monday!

**Comment by simonque** [comment]
/cc @nesquena and @thecodepath @vibhorB 
We have finished Milestone 2 and have included the demo GIFs.

**Comment by simonque** [comment]
I created the "m2" branch to preserve our work. We are making further changes to the code for post-Milestone 2.

**Comment by vibhorB** [comment]
:+1: Good work PartyView team, very impressed with the flow of app and clean UI.

Spend more time in adding polish to UI and adding small features to make user experience better. These tasks are what will make your app stand out from the crowd and bring a lot of value. Keep working on a story also for the demo, a good story wins half the battle of presenting the app. Looking forward to your final product.
