### ISSUE TITLE
Better error handling of new event activity

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#37]
Should have some requirements for fields being set.
Also, onPostExecute() in NewEventActivity.createEvent() should handle a null location.

**Comment by simonque** [comment]
For now, I've created an empty location object: https://github.com/eecsninja/partyview/commit/f7b21fa84bf048f8775d73fe5d4ff7b390d73314

**Comment by mydiemho** [comment]
Requirements for field:
1) Title - required
2) Start & End time - optional 
    a) End time must be greater than start time
3) Location - required
4) Description - optional
5) Invites - (at least 1?)

If any required field is missing or incorrect, notify user to enter missing/correct info

**Comment by simonque** [comment]
Also, if you move the start time, the end time should move by the same amount, to keep the duration the same. How does that sound?

**Comment by mydiemho** [comment]
depends on how much time other issues take, I might move the feature for time changing to M3 (optional)

**Comment by mydiemho** [comment]
everything done.

need to add:
1)  if you move the start time, the end time should move by the same amount, to keep the duration the same.

**Comment by mydiemho** [comment]
maintain duration between start and end time when changing start time will be in M3
