### ISSUE TITLE
Accepted events should show up in accepted events list

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#38]
This is for events that the current user didn't create. Right now, they don't show up there unless you restart the app.

**Comment by mydiemho** [comment]
I can't reproduce this issue.   Is this still happening with the latest pull?

**Comment by simonque** [comment]
I'll take care of it. Assign it to me.

**Comment by simonque** [comment]
Oh just figured out how to assign it on github app

**Comment by simonque** [comment]
I can't repro it so I'm closing for now. we should do a clean sweep tomorrow (erase existing events) and try it afresh just to make sure, though.
