### ISSUE TITLE
One of my accepted events still displays "join" button in detailed view

### ISSUE THREAD

**Issue by simonque** [simonque/partyview#39]
All the other events show "leave" button.
This is the first event in the list. Not sure if that makes a diff.
I've shared my login info in case you'd like to try it.

**Comment by mydiemho** [comment]
accepted doesn't mean automatically join.  I looked at the data on Parse and the event show "join" button because its status is "accepted" and the other events' statuses are "present"

**Comment by mydiemho** [comment]
I don't think this is an issue.  Can you close this?

**Comment by simonque** [comment]
I'll inspect it and close it if it's not a problem.

**Comment by simonque** [comment]
Let's try this tomorrow in person, with a clean slate, see if it still comes back. For now I'll assume it's closed.
