### ISSUE TITLE
Updating event issues

### ISSUE THREAD

**Issue by brung** [simonque/partyview#46]
Name is not updated on return from update screen
Created a duplicate event with everyone on original invite appearing twice.

**Comment by simonque** [comment]
Updating event in parent activity:
https://github.com/eecsninja/partyview/commit/7733e1d42d034bdf4688125117a7480299667f9f

Do not create duplicates:
https://github.com/eecsninja/partyview/commit/84da36f32329e3102fb4b9d2c047b791c8d96716

**Comment by simonque** [comment]
And this: https://github.com/eecsninja/partyview/commit/a1dc3efa756c8d4555bd7b461e5d5c2e03fd0581
