### ISSUE TITLE
Change attendees actionbar icon to be a button under mini map

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#54]
The icon is not very intuitive .  

http://33.media.tumblr.com/dd2e6a2ad7cece5951e453fe8f1def78/tumblr_n780arnbcr1r2wjwko3_1280.png

**Comment by sandramngo** [comment]
https://github.com/eecsninja/partyview/commit/06124ebe96f1317dbac79d2d074f206de73a801f
