### ISSUE TITLE
Change attendees actionbar icon to be a button under mini map

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#55]
The icon is not very intuitive. Replace with button similar to "People" in Sunrise.

![tumblr_n780arnbcr1r2wjwko3_1280](https://cloud.githubusercontent.com/assets/1634185/3568587/f9a113a6-0b32-11e4-947c-e17c6d571def.png)

**Comment by sandramngo** [comment]
duplicate https://github.com/eecsninja/partyview/commit/06124ebe96f1317dbac79d2d074f206de73a801f
