### ISSUE TITLE
add scrollview to editable views

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#59]

**Comment by simonque** [comment]
https://github.com/eecsninja/partyview/commit/5b8728a976aadb3ece6e2725302d227b5443c581

Still not sure how to make it actually manually scroll though.

**Comment by simonque** [comment]
Reverted the previous commit and replaced it with:
https://github.com/eecsninja/partyview/commit/744334e820cbc650356e900f20318d6ac86a7dcc
