### ISSUE TITLE
add refresh to event list

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#61]
1) either pull-to-refresh or automatic period refresh or both

**Comment by simonque** [comment]
Implemented pull down refresh:
https://github.com/eecsninja/partyview/commit/e2ebd99ab663087e2c7c3804a8097d8fb43b841d

It would be good to have a notification-based refresh though.

**Comment by simonque** [comment]
Notification based refresh:
https://github.com/eecsninja/partyview/commit/2ad7331a69576511cbca63da64ad274283393b27
