### ISSUE TITLE
Send invitations

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#7]
Acceptance Criteria:

0) Send invites by starting intent to send email.
    \* Passing data (email) through intents

**Comment by sandramngo** [comment]
https://github.com/splitwise/TokenAutoComplete for typing usernames and adding to invite list

**Comment by mydiemho** [comment]
event creation generate associated eventUser objects (https://github.com/eecsninja/partyview/commit/98229fdb95ec938163ffa995aecfee7281f7357a) which will be used to push notifications (#21)
