### ISSUE TITLE
Put icon on Invites for pending invites

### ISSUE THREAD

**Issue by brung** [simonque/partyview#71]
Show a count on invites tab for pending invites 
Invites (2)

**Comment by simonque** [comment]
Doesn't have to be icons right? Can just be text.

**Comment by mydiemho** [comment]
https://github.com/eecsninja/partyview/commit/cbdeed13e9ecf9a0b447c2747085865123c68181

show it show (0) or nothing if the list is empty?

**Comment by brung** [comment]
I'd probably not show (0) if the list is empty but its ok to show (0).  Even better is if there was something to indicate unseen invites.

**Comment by brung** [comment]
And yah can be text. Not sure why i said icon :)

**Comment by mydiemho** [comment]
https://github.com/eecsninja/partyview/commit/d20f1fe2ea602a3f69fec73a1df9b913c52d6963
