### ISSUE TITLE
Set up map

### ISSUE THREAD

**Issue by mydiemho** [simonque/partyview#9]
0) display fake location

![image](https://cloud.githubusercontent.com/assets/1634185/3451596/ec9e0678-019b-11e4-9296-28ef4a274763.png)

**Comment by mydiemho** [comment]
ballon to annotate pin:

https://github.com/airbnb/android-mapviewballoons

**Comment by sandramngo** [comment]
http://mygeoposition.com/

**Comment by sandramngo** [comment]
https://github.com/eecsninja/partyview/commit/06c9cbbd72900c4a1b29c54a405317cc44f3e64a

**Comment by sandramngo** [comment]
https://github.com/eecsninja/partyview/commit/38a79aab55205bb964384ccc059a76c14ddc5e1b
